# Generated by Django 2.1 on 2018-08-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('file_upload', models.FileField(blank=True, upload_to='media')),
            ],
        ),
    ]
