# Generated by Django 2.1 on 2018-09-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_challenge_events', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='event_id',
        ),
    ]
