# Generated by Django 2.1 on 2018-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_challenge_events', '0004_auto_20180908_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='event',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
